'use strict';
const fullName = 'Valentina Osorio';
console.log('fullName:', fullName);
const isCool = true;
console.log('isCool:', isCool);
const totalPets = 2;
console.log('totalPets:', totalPets);
console.log('typeof fullName:', typeof fullName);
console.log('typeof isCool:', typeof isCool);
console.log('typeof totalPets:', typeof totalPets);
const empty = null;
console.log('empty:', empty);
console.log('typeof empty:', typeof empty);
let nothing;
console.log('nothing:', nothing);
console.log('typeof nothing:', typeof nothing);
