'use strict';
const arr = ['red', 'white', 'blue'];
const colors = arr;
console.log('colors array:', arr);
console.log('value of color [0]:', arr[0]);
console.log('value of color [1]:', arr[1]);
console.log('value of color [2]:', arr[2]);
const templateLiteral = `America is ${arr[0]}, ${arr[1]}, and ${arr[2]}.`;
console.log(templateLiteral);
arr[2] = `green`;
console.log(arr[2]);
const Mexico = `Mexico is ${arr[0]}, ${arr[1]}, and ${arr[2]}.`;
console.log(Mexico);
console.log('new colors array:', arr);
console.log('typeof colors array:', typeof arr);
const arr2 = ['Val', 'Marly', 'Jess', 'Trouble'];
const students = arr2;
const numberOfStudents = arr2.length;
console.log('There are ' + numberOfStudents + ' students in the class.');
const lastIndex = arr2[numberOfStudents - 1];
const lastStudent = lastIndex;
console.log('The last student in the array is', lastStudent);
console.log('students array:', students);
console.log('typeof students array:', typeof students);
