'use strict';
const width = 2;
const height = 2;
const area = width * height;
console.log('area:', area);
console.log('typeof area:', typeof area);
const bill = 10;
const payment = 20;
const change = payment - bill;
console.log('change:', change);
console.log('typeof change:', typeof change);
const quizzes = 5;
const midterm = 10;
const final = 15;
const grade = (quizzes + midterm + final) / 3;
console.log('grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName = 'Valentina ';
const lastName = 'Osorio';
const fullName = firstName + lastName;
console.log('fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const pH = 6;
const isAcidic = pH < 7;
console.log('isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
const headCount = 10;
const isSparta = headCount == 300;
console.log('isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
const motto = fullName + ' is the GOAT';
console.log('motto:', motto);
console.log('typeof motto:', typeof motto);
